.TH DWM_TIME 1 dwm_time\-VERSION
.SH NAME
dwm_time \- show current time in dwm's status bar
.SH SYNOPSIS
.B dwm_time
.SH DESCRIPTION
dwm_time shows the current time in dwm's status bar. Edit the file
config.h to change the used time zone. Do not forget to recompile
dwm_time afterwards.
.SH OPTIONS
dwm_time does not have any command line options.
.SH CUSTOMIZATION
The behaviour of dwm_time can be changed by editing the file config.h
and (re)compiling the source code.
.SH SEE ALSO
.BR dwm (1)
